// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MessageHub.MeltModels
{
    public partial class FromBiz
    {
        public int FromBizId { get; set; }
        public int? SourceId { get; set; }
        public string MessageName { get; set; }
        public string Message { get; set; }
        public int MessageStateId { get; set; }
        public DateTime QueuedTime { get; set; }
        public DateTime? ProcessedTime { get; set; }
        public int? TransactionId { get; set; }
        public string ErrorDescription { get; set; }
        public string L4transactionId { get; set; }
        public string OrderNumber { get; set; }
        public string OrderItem { get; set; }
        public string HeatNumber { get; set; }
        public string Ingot { get; set; }
        public string Lot { get; set; }
        public string ResubmittedByUserId { get; set; }

        public virtual MessageState MessageState { get; set; }
    }
}