// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MessageHub.MeltModels
{
    public partial class MessageState
    {
        public MessageState()
        {
            FromBizs = new HashSet<FromBiz>();
            ToBizs = new HashSet<ToBiz>();
        }

        public int MessageStateId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<FromBiz> FromBizs { get; set; }
        public virtual ICollection<ToBiz> ToBizs { get; set; }
    }
}