// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MessageHub.MeltModels
{
    public partial class VMsgHubMessageTypesFromBiz
    {
        public string MessageName { get; set; }
    }
}