// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MessageHub.SX32Models
{
    public partial class MessageState
    {
        public MessageState()
        {
            FromBizs = new HashSet<FromBiz>();
            ToBizs = new HashSet<ToBiz>();
        }

        public int MessageStateId { get; set; }
        public string Name { get; set; }
        /// <summary>
        /// Description value for this record
        /// </summary>
        public string Description { get; set; }
        public DateTimeOffset LastUpdateOn { get; set; }
        public string LastUpdateBy { get; set; }
        public DateTimeOffset CreatedOn { get; set; }
        public string CreatedBy { get; set; }

        public virtual ICollection<FromBiz> FromBizs { get; set; }
        public virtual ICollection<ToBiz> ToBizs { get; set; }
    }
}