// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MessageHub.NDTModels
{
    public partial class FromBiz
    {
        public int FromBizId { get; set; }
        public string MessageName { get; set; }
        public string Message { get; set; }
        public int MessageStateId { get; set; }
        public DateTime QueuedTime { get; set; }
        public DateTime? ProcessedTime { get; set; }
        public string ErrorDescription { get; set; }
        public bool AlertSent { get; set; }
        public string TransactionId { get; set; }
        public int? ToBizId { get; set; }
        public bool? AckReceived { get; set; }
        public bool? Response { get; set; }
        public bool? StatusReceived { get; set; }
        public string OrderNumber { get; set; }
        public string OrderItem { get; set; }
        public string Heat { get; set; }
        public string Ingot { get; set; }
        public string Lot { get; set; }
        public string LineId { get; set; }

        public virtual MessageState MessageState { get; set; }
    }
}